# Generated by Django 5.2.5 on 2025-11-29 02:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(db_column='id_cita', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora', models.TimeField(db_column='hora')),
                ('motivo', models.TextField(db_column='motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada'), ('mantenimiento', 'Mantenimiento')], db_column='estado', default='pendiente', max_length=20)),
                ('reprogramaciones', models.IntegerField(db_column='reprogramaciones', default=0, help_text='Número de veces que el paciente reprogramó esta cita.', validators=[django.core.validators.MinValueValidator(0)])),
                ('cancelada_en', models.DateTimeField(blank=True, db_column='cancelada_en', help_text='Fecha/hora exacta en que el PACIENTE canceló. Nulo si canceló staff/odontólogo.', null=True)),
                ('cancelada_por_rol', models.IntegerField(blank=True, db_column='cancelada_por_rol', help_text='Rol que canceló: 1,2,3,4. Si fue staff/odo, no se aplica cooldown.', null=True)),
                ('ausentismo', models.BooleanField(db_column='ausentismo', default=False, help_text='Marca si la cita fue cancelada por inasistencia del paciente (ausentismo confirmado por el odontólogo).')),
                ('reprogramada_en', models.DateTimeField(blank=True, db_column='reprogramada_en', help_text='Fecha/hora en que esta cita fue marcada para reprogramación (por operación masiva).', null=True)),
                ('reprogramada_por_rol', models.IntegerField(blank=True, db_column='reprogramada_por_rol', help_text='Rol que marcó la reprogramación masiva (1=Admin, etc.).', null=True)),
                ('batch_id', models.UUIDField(blank=True, db_column='batch_id', db_index=True, help_text='Identificador del lote de operación masiva (para filtrar y reportar).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('whatsapp_message_sid', models.CharField(blank=True, db_column='whatsapp_message_sid', help_text='SID del mensaje de recordatorio enviado por WhatsApp.', max_length=64, null=True)),
                ('recordatorio_enviado_at', models.DateTimeField(blank=True, db_column='recordatorio_enviado_at', help_text='Marca de tiempo cuando se envió el recordatorio por WhatsApp.', null=True)),
                ('confirmacion_fuente', models.CharField(blank=True, db_column='confirmacion_fuente', help_text='whatsapp | web | recepcion', max_length=16, null=True)),
            ],
            options={
                'db_table': 'cita',
                'ordering': ['fecha', 'hora', 'id_cita'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(db_column='id_configuracion', primary_key=True, serialize=False)),
                ('celular_contacto', models.CharField(db_column='celular_contacto', default='0999999999', help_text='Celular de contacto del consultorio (formato E.164 recomendado).', max_length=20, validators=[django.core.validators.RegexValidator(message='El celular de contacto debe tener entre 9 y 15 dígitos (E.164: +593XXXXXXXXX).', regex='^\\+?\\d{9,15}$')])),
                ('max_citas_activas', models.IntegerField(db_column='max_citas_activas', default=1, help_text='Número máximo de citas activas (pendiente/confirmada) que un paciente puede tener simultáneamente.', validators=[django.core.validators.MinValueValidator(1)])),
                ('horas_confirmar_desde', models.IntegerField(db_column='horas_confirmar_desde', default=24, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_confirmar_hasta', models.IntegerField(db_column='horas_confirmar_hasta', default=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_autoconfirmar', models.IntegerField(db_column='horas_autoconfirmar', default=24, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_citas_dia', models.IntegerField(db_column='max_citas_dia', default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cooldown_dias', models.IntegerField(db_column='cooldown_dias', default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_reprogramaciones', models.IntegerField(db_column='max_reprogramaciones', default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_horas_anticipacion', models.IntegerField(db_column='min_horas_anticipacion', default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_consultorio', models.AutoField(db_column='id_consultorio', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='numero', max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'consultorio',
                'ordering': ['id_consultorio'],
            },
        ),
        migrations.CreateModel(
            name='PagoCita',
            fields=[
                ('id_pago_cita', models.AutoField(db_column='id_pago_cita', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, help_text='Monto total pagado por la cita.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], db_column='metodo_pago', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado')], db_column='estado_pago', default='pendiente', max_length=20)),
                ('comprobante', models.URLField(blank=True, db_column='comprobante', help_text='URL del comprobante de pago en Cloudinary.', max_length=500, null=True)),
                ('observacion', models.TextField(blank=True, db_column='observacion', null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, db_column='fecha_pago', help_text='Fecha y hora en que se registró el pago.', null=True)),
                ('reembolsado_en', models.DateTimeField(blank=True, db_column='reembolsado_en', help_text='Fecha y hora en que se efectuó el reembolso (si aplica).', null=True)),
                ('motivo_reembolso', models.TextField(blank=True, db_column='motivo_reembolso', help_text='Motivo por el cual se efectuó el reembolso.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'pago_cita',
                'ordering': ['-created_at'],
            },
        ),
    ]
