# Generated by Django 5.2.5 on 2025-08-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(db_column='id_cita', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('hora', models.TimeField(db_column='hora')),
                ('motivo', models.TextField(db_column='motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], db_column='estado', default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'cita',
                'ordering': ['fecha', 'hora', 'id_cita'],
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_consultorio', models.AutoField(db_column='id_consultorio', primary_key=True, serialize=False)),
                ('numero', models.CharField(db_column='numero', max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'consultorio',
                'ordering': ['id_consultorio'],
            },
        ),
    ]
