# Generated by Django 5.2.5 on 2025-08-31 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('odontologos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_odontologo',
            field=models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='odontologos.odontologo'),
        ),
    ]
