# Generated by Django 5.2.5 on 2025-11-29 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.paciente'),
        ),
        migrations.AddIndex(
            model_name='consultorio',
            index=models.Index(fields=['estado'], name='idx_consultorio_estado'),
        ),
        migrations.AddIndex(
            model_name='consultorio',
            index=models.Index(fields=['numero'], name='idx_consultorio_numero'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_consultorio',
            field=models.ForeignKey(db_column='id_consultorio', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.consultorio'),
        ),
        migrations.AddField(
            model_name='pagocita',
            name='id_cita',
            field=models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='citas.cita'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_odontologo', 'fecha'], name='idx_cita_odo_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_consultorio', 'fecha'], name='idx_cita_consul_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_paciente', 'fecha'], name='idx_cita_paciente_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha'], name='idx_cita_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_paciente', 'id_odontologo', 'cancelada_en'], name='idx_cita_po_canceladaen'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cancelada_por_rol', 'cancelada_en'], name='idx_cita_cancel_porrol_en'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'id_consultorio', 'fecha'], name='idx_cita_est_cons_fecha'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('id_odontologo', 'fecha', 'hora'), name='uq_cita_odo_fecha_hora_activa'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('id_consultorio', 'fecha', 'hora'), name='uq_cita_consul_fecha_hora_activa'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('id_paciente', 'fecha', 'hora'), name='uq_cita_paciente_fecha_hora_activa'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('hora__minute', 0)), name='ck_cita_minuto_cero'),
        ),
        migrations.AddIndex(
            model_name='pagocita',
            index=models.Index(fields=['estado_pago'], name='idx_pago_estado'),
        ),
        migrations.AddIndex(
            model_name='pagocita',
            index=models.Index(fields=['metodo_pago'], name='idx_pago_metodo'),
        ),
        migrations.AddIndex(
            model_name='pagocita',
            index=models.Index(fields=['fecha_pago'], name='idx_pago_fecha'),
        ),
    ]
