# Generated by Django 5.2.5 on 2025-08-31 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.paciente'),
        ),
        migrations.AddIndex(
            model_name='consultorio',
            index=models.Index(fields=['estado'], name='idx_consultorio_estado'),
        ),
        migrations.AddIndex(
            model_name='consultorio',
            index=models.Index(fields=['numero'], name='idx_consultorio_numero'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_consultorio',
            field=models.ForeignKey(db_column='id_consultorio', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.consultorio'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_odontologo', 'fecha'], name='idx_cita_odo_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_consultorio', 'fecha'], name='idx_cita_consul_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_paciente', 'fecha'], name='idx_cita_paciente_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha'], name='idx_cita_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('id_odontologo', 'fecha', 'hora'), name='uq_cita_odo_fecha_hora_activa'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('id_consultorio', 'fecha', 'hora'), name='uq_cita_consul_fecha_hora_activa'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('id_paciente', 'fecha', 'hora'), name='uq_cita_paciente_fecha_hora_activa'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('hora__minute', 0)), name='ck_cita_minuto_cero'),
        ),
    ]
