# Generated by Django 5.2.5 on 2025-09-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_initial'),
        ('odontologos', '0002_initial'),
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, db_column='cancelada_en', help_text='Fecha/hora exacta en que el PACIENTE canceló. Nulo si canceló staff/odontólogo.', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='cancelada_por_rol',
            field=models.PositiveSmallIntegerField(blank=True, db_column='cancelada_por_rol', help_text='Rol que canceló: 1,2,3,4. Si fue staff/odo, no se aplica cooldown.', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='reprogramaciones',
            field=models.PositiveSmallIntegerField(db_column='reprogramaciones', default=0, help_text='Número de veces que el paciente reprogramó esta cita.'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['id_paciente', 'id_odontologo', 'cancelada_en'], name='idx_cita_po_canceladaen'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cancelada_por_rol', 'cancelada_en'], name='idx_cita_cancel_porrol_en'),
        ),
    ]
