# Generated by Django 5.2.5 on 2025-09-18 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_cancelada_en_cita_cancelada_por_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cancelada_por_rol',
            field=models.IntegerField(blank=True, db_column='cancelada_por_rol', help_text='Rol que canceló: 1,2,3,4. Si fue staff/odo, no se aplica cooldown.', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='reprogramaciones',
            field=models.IntegerField(db_column='reprogramaciones', default=0, help_text='Número de veces que el paciente reprogramó esta cita.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
