# Generated by Django 5.2.5 on 2025-09-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_cita_cancelada_por_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='confirmacion_fuente',
            field=models.CharField(blank=True, db_column='confirmacion_fuente', help_text='whatsapp | web | recepcion', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado_at',
            field=models.DateTimeField(blank=True, db_column='recordatorio_enviado_at', help_text='Marca de tiempo cuando se envió el recordatorio por WhatsApp.', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='whatsapp_message_sid',
            field=models.CharField(blank=True, db_column='whatsapp_message_sid', help_text='SID del mensaje de recordatorio enviado por WhatsApp.', max_length=64, null=True),
        ),
    ]
