# Generated by Django 5.2.5 on 2025-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_confirmacion_fuente_and_more'),
        ('odontologos', '0003_bloqueodia_idx_bloqueo_recurrente_mmdd_od'),
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='batch_id',
            field=models.UUIDField(blank=True, db_column='batch_id', db_index=True, help_text='Identificador del lote de operación masiva (para filtrar y reportar).', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='reprogramada_en',
            field=models.DateTimeField(blank=True, db_column='reprogramada_en', help_text='Fecha/hora en que esta cita fue marcada para reprogramación (por operación masiva).', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='reprogramada_por_rol',
            field=models.IntegerField(blank=True, db_column='reprogramada_por_rol', help_text='Rol que marcó la reprogramación masiva (1=Admin, etc.).', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada'), ('reprogramacion', 'Reprogramación')], db_column='estado', default='pendiente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'id_consultorio', 'fecha'], name='idx_cita_est_cons_fecha'),
        ),
    ]
