# Generated by Django 5.2.5 on 2025-11-29 02:45

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoDia',
            fields=[
                ('id_bloqueo', models.AutoField(db_column='id_bloqueo', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fecha')),
                ('recurrente_anual', models.BooleanField(db_column='recurrente_anual', default=False)),
                ('motivo', models.TextField(blank=True, db_column='motivo', null=True)),
                ('grupo', models.UUIDField(db_column='grupo', db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'bloqueo_dia',
                'ordering': ['id_bloqueo'],
            },
        ),
        migrations.CreateModel(
            name='OdontologoEspecialidad',
            fields=[
                ('id_odo_esp', models.AutoField(db_column='id_odo_esp', primary_key=True, serialize=False)),
                ('universidad', models.CharField(blank=True, db_column='universidad', max_length=150, null=True)),
                ('estado', models.BooleanField(db_column='estado', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'odontologo_especialidad',
                'ordering': ['id_odo_esp'],
            },
        ),
        migrations.CreateModel(
            name='OdontologoHorario',
            fields=[
                ('id_horario', models.AutoField(db_column='id_horario', primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], db_column='dia_semana')),
                ('hora_inicio', models.TimeField(db_column='hora_inicio')),
                ('hora_fin', models.TimeField(db_column='hora_fin')),
                ('vigente', models.BooleanField(db_column='vigente', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'odontologo_horario',
                'ordering': ['id_horario'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(db_column='id_especialidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'especialidad',
                'ordering': ['id_especialidad'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uq_especialidad_nombre_ci')],
            },
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id_odontologo', models.AutoField(db_column='id_odontologo', primary_key=True, serialize=False)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_consultorio_defecto', models.ForeignKey(blank=True, db_column='id_consultorio_defecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontologos_por_defecto', to='citas.consultorio')),
            ],
            options={
                'db_table': 'odontologo',
                'ordering': ['id_odontologo'],
            },
        ),
    ]
