# Generated by Django 5.2.5 on 2025-11-29 02:45

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontologos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='odontologo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloqueodia',
            name='id_odontologo',
            field=models.ForeignKey(blank=True, db_column='id_odontologo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='odontologos.odontologo'),
        ),
        migrations.AddField(
            model_name='odontologoespecialidad',
            name='id_especialidad',
            field=models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.CASCADE, related_name='odontologos', to='odontologos.especialidad'),
        ),
        migrations.AddField(
            model_name='odontologoespecialidad',
            name='id_odontologo',
            field=models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='odontologos.odontologo'),
        ),
        migrations.AddField(
            model_name='odontologohorario',
            name='id_odontologo',
            field=models.ForeignKey(db_column='id_odontologo', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='odontologos.odontologo'),
        ),
        migrations.AddIndex(
            model_name='bloqueodia',
            index=models.Index(fields=['fecha'], name='idx_bloqueo_fecha'),
        ),
        migrations.AddIndex(
            model_name='bloqueodia',
            index=models.Index(fields=['id_odontologo', 'fecha'], name='idx_bloqueo_odo_fecha'),
        ),
        migrations.AddIndex(
            model_name='bloqueodia',
            index=models.Index(fields=['grupo'], name='idx_bloqueo_grupo'),
        ),
        migrations.AddIndex(
            model_name='bloqueodia',
            index=models.Index(models.F('recurrente_anual'), django.db.models.functions.datetime.ExtractMonth('fecha'), django.db.models.functions.datetime.ExtractDay('fecha'), models.F('id_odontologo'), name='idx_bloqueo_recurrente_mmdd_od'),
        ),
        migrations.AddConstraint(
            model_name='bloqueodia',
            constraint=models.UniqueConstraint(fields=('id_odontologo', 'fecha'), name='uq_bloqueo_por_dia_por_odo'),
        ),
        migrations.AddConstraint(
            model_name='bloqueodia',
            constraint=models.UniqueConstraint(condition=models.Q(('id_odontologo__isnull', True)), fields=('fecha',), name='uq_bloqueo_global_por_dia'),
        ),
        migrations.AddIndex(
            model_name='odontologoespecialidad',
            index=models.Index(fields=['id_odontologo', 'estado'], name='idx_odoesp_odo_estado'),
        ),
        migrations.AddIndex(
            model_name='odontologoespecialidad',
            index=models.Index(fields=['id_especialidad', 'estado'], name='idx_odoesp_esp_estado'),
        ),
        migrations.AddConstraint(
            model_name='odontologoespecialidad',
            constraint=models.UniqueConstraint(fields=('id_odontologo', 'id_especialidad'), name='uq_odo_especialidad'),
        ),
        migrations.AddIndex(
            model_name='odontologohorario',
            index=models.Index(fields=['id_odontologo', 'dia_semana', 'vigente'], name='idx_horario_odo_dia_vig'),
        ),
        migrations.AddConstraint(
            model_name='odontologohorario',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_horario_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='odontologohorario',
            constraint=models.CheckConstraint(condition=models.Q(('dia_semana__gte', 0), ('dia_semana__lte', 6)), name='ck_dia_semana_valido'),
        ),
        migrations.AddConstraint(
            model_name='odontologohorario',
            constraint=models.UniqueConstraint(fields=('id_odontologo', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uq_horario_exact_duplicate'),
        ),
    ]
