# Generated by Django 5.2.5 on 2025-09-09 19:26

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bloqueodia',
            index=models.Index(models.F('recurrente_anual'), django.db.models.functions.datetime.ExtractMonth('fecha'), django.db.models.functions.datetime.ExtractDay('fecha'), models.F('id_odontologo'), name='idx_bloqueo_recurrente_mmdd_od'),
        ),
    ]
