# Generated by Django 5.2.5 on 2025-11-29 02:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha_medica', models.AutoField(db_column='id_ficha_medica', primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True, db_column='observacion', null=True)),
                ('diagnostico', models.TextField(blank=True, db_column='diagnostico', null=True)),
                ('tratamiento', models.TextField(blank=True, db_column='tratamiento', null=True)),
                ('comentarios', models.TextField(blank=True, db_column='comentarios', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_cita', models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.PROTECT, related_name='ficha_medica', to='citas.cita')),
            ],
            options={
                'db_table': 'ficha_medica',
                'ordering': ['id_ficha_medica'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id_archivo_adjunto', models.AutoField(db_column='id_archivo_adjunto', primary_key=True, serialize=False)),
                ('archivo_url', models.URLField(blank=True, db_column='archivo_url', help_text='URL del archivo en Cloudinary', max_length=500, null=True)),
                ('nombre_original', models.TextField(blank=True, db_column='nombre_original')),
                ('mime_type', models.CharField(blank=True, db_column='mime_type', max_length=100)),
                ('tamano_bytes', models.IntegerField(blank=True, db_column='tamano_bytes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum_sha256', models.CharField(blank=True, db_column='checksum_sha256', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_ficha_medica', models.ForeignKey(db_column='id_ficha_medica', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='fichas_medicas.fichamedica')),
            ],
            options={
                'db_table': 'archivo_adjunto',
                'ordering': ['id_archivo_adjunto'],
            },
        ),
        migrations.AddIndex(
            model_name='fichamedica',
            index=models.Index(fields=['id_cita'], name='idx_ficha_cita'),
        ),
        migrations.AddIndex(
            model_name='archivoadjunto',
            index=models.Index(fields=['id_ficha_medica'], name='idx_adj_ficha'),
        ),
        migrations.AddIndex(
            model_name='archivoadjunto',
            index=models.Index(fields=['created_at'], name='idx_adj_created'),
        ),
    ]
