# Generated by Django 5.2.5 on 2025-08-31 03:52

import django.core.validators
import django.db.models.deletion
import fichas_medicas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id_ficha_medica', models.AutoField(db_column='id_ficha_medica', primary_key=True, serialize=False)),
                ('observacion', models.TextField(blank=True, db_column='observacion', null=True)),
                ('diagnostico', models.TextField(blank=True, db_column='diagnostico', null=True)),
                ('tratamiento', models.TextField(blank=True, db_column='tratamiento', null=True)),
                ('comentarios', models.TextField(blank=True, db_column='comentarios', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], db_column='estado', default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_cita', models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.PROTECT, related_name='ficha_medica', to='citas.cita')),
            ],
            options={
                'db_table': 'ficha_medica',
                'ordering': ['id_ficha_medica'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id_archivo_adjunto', models.AutoField(db_column='id_archivo_adjunto', primary_key=True, serialize=False)),
                ('archivo', models.FileField(blank=True, db_column='archivo', null=True, upload_to=fichas_medicas.models.adjunto_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('mime_type', models.CharField(blank=True, db_column='mime_type', max_length=100)),
                ('nombre_original', models.TextField(blank=True, db_column='nombre_original')),
                ('tamano_bytes', models.BigIntegerField(blank=True, db_column='tamano_bytes', null=True)),
                ('checksum_sha256', models.CharField(blank=True, db_column='checksum_sha256', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_ficha_medica', models.ForeignKey(db_column='id_ficha_medica', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='fichas_medicas.fichamedica')),
            ],
            options={
                'db_table': 'archivo_adjunto',
                'ordering': ['id_archivo_adjunto'],
            },
        ),
        migrations.AddIndex(
            model_name='fichamedica',
            index=models.Index(fields=['id_cita'], name='idx_ficha_cita'),
        ),
        migrations.AddIndex(
            model_name='fichamedica',
            index=models.Index(fields=['estado', 'created_at'], name='idx_ficha_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='archivoadjunto',
            index=models.Index(fields=['id_ficha_medica'], name='idx_adj_ficha'),
        ),
        migrations.AddIndex(
            model_name='archivoadjunto',
            index=models.Index(fields=['created_at'], name='idx_adj_created'),
        ),
    ]
