# Generated by Django 5.2.5 on 2025-09-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fichamedica',
            name='idx_ficha_estado_fecha',
        ),
        migrations.RemoveField(
            model_name='fichamedica',
            name='estado',
        ),
    ]
