# Generated by Django 5.2.5 on 2025-12-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo_url',
            field=models.TextField(blank=True, db_column='archivo_url', help_text='URL encriptada del archivo en Cloudinary', null=True),
        ),
    ]
