# Generated by Django 5.2.5 on 2025-09-18 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_medicas', '0002_remove_fichamedica_idx_ficha_estado_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='tamano_bytes',
            field=models.IntegerField(blank=True, db_column='tamano_bytes', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
