# Generated by Django 5.2.5 on 2025-11-29 02:45

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(db_column='id_paciente', primary_key=True, serialize=False)),
                ('contacto_emergencia_nom', models.CharField(db_column='contacto_emergencia_nom', max_length=100)),
                ('contacto_emergencia_cel', models.CharField(db_column='contacto_emergencia_cel', max_length=15, validators=[django.core.validators.RegexValidator(message='El número debe tener entre 9 y 15 dígitos (formato E.164: +593XXXXXXXXX).', regex='^\\+?\\d{9,15}$')])),
                ('contacto_emergencia_par', models.CharField(choices=[('hijos', 'Hijos'), ('padres', 'Padres'), ('hermanos', 'Hermanos'), ('abuelos', 'Abuelos'), ('esposos', 'Esposos'), ('otros', 'Otros')], db_column='contacto_emergencia_par', max_length=50)),
                ('contacto_emergencia_email', models.EmailField(blank=True, db_column='contacto_emergencia_email', help_text='Email del contacto de emergencia (obligatorio para menores sin email propio)', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'paciente',
                'ordering': ['id_paciente'],
            },
        ),
        migrations.CreateModel(
            name='PacienteAntecedente',
            fields=[
                ('id_paciente_antecedente', models.AutoField(db_column='id_paciente_antecedente', primary_key=True, serialize=False)),
                ('relacion_familiar', models.CharField(choices=[('abuelos', 'Abuelos'), ('padres', 'Padres'), ('hermanos', 'Hermanos'), ('propio', 'Propio')], db_column='relacion_familiar', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'paciente_antecedente',
                'ordering': ['id_paciente_antecedente'],
            },
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id_antecedente', models.AutoField(db_column='id_antecedente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'antecedente',
                'ordering': ['id_antecedente'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='uq_antecedente_nombre_ci')],
            },
        ),
    ]
