# Generated by Django 5.2.5 on 2025-08-31 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacienteantecedente',
            name='id_antecedente',
            field=models.ForeignKey(db_column='id_antecedente', on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='pacientes.antecedente'),
        ),
        migrations.AddField(
            model_name='pacienteantecedente',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente'),
        ),
        migrations.AddConstraint(
            model_name='pacienteantecedente',
            constraint=models.UniqueConstraint(fields=('id_paciente', 'id_antecedente', 'relacion_familiar'), name='uq_paciente_antecedente_rel'),
        ),
    ]
