# Generated by Django 5.2.5 on 2025-11-29 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='rol', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'rol',
                'ordering': ['id_rol'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='cedula', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos.', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, db_column='email', help_text='Email del usuario. Para menores sin email, se genera automáticamente.', max_length=254, null=True, unique=True)),
                ('celular', models.CharField(blank=True, db_column='celular', help_text='Celular del usuario (opcional para menores sin celular propio)', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El celular debe tener entre 9 y 15 dígitos (formato E.164: +593XXXXXXXXX).', regex='^\\+?\\d{9,15}$')])),
                ('primer_nombre', models.CharField(db_column='primer_nombre', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, db_column='segundo_nombre', max_length=100, null=True)),
                ('primer_apellido', models.CharField(db_column='primer_apellido', max_length=100)),
                ('segundo_apellido', models.CharField(db_column='segundo_apellido', max_length=100)),
                ('fecha_nacimiento', models.DateField(db_column='fecha_nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='sexo', max_length=1)),
                ('tipo_sangre', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Desconocido', 'Desconocido')], db_column='tipo_sangre', default='Desconocido', max_length=12)),
                ('foto', models.URLField(blank=True, db_column='foto', help_text='URL de la foto del usuario', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('intentos_fallidos', models.IntegerField(db_column='intentos_fallidos', default=0, help_text='Contador de intentos de login fallidos consecutivos. Al llegar a 20 se desactiva la cuenta automáticamente.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('ultimo_intento_fallido', models.DateTimeField(blank=True, db_column='ultimo_intento_fallido', help_text='Timestamp del último intento fallido', null=True)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, db_column='bloqueado_hasta', help_text='Fecha y hora hasta la cual la cuenta está bloqueada temporalmente', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['id_usuario'],
            },
        ),
        migrations.CreateModel(
            name='IntentosLogin',
            fields=[
                ('id_intento', models.AutoField(db_column='id_intento', primary_key=True, serialize=False)),
                ('cedula_intentada', models.CharField(db_column='cedula_intentada', max_length=10)),
                ('ip_address', models.GenericIPAddressField(db_column='ip_address')),
                ('exitoso', models.BooleanField(db_column='exitoso', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intentos_login',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cedula_intentada', '-created_at'], name='intentos_lo_cedula__d8b134_idx'), models.Index(fields=['ip_address', '-created_at'], name='intentos_lo_ip_addr_72e463_idx')],
            },
        ),
    ]
