# Generated by Django 5.2.5 on 2025-08-31 03:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='rol', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'rol',
                'ordering': ['id_rol'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('primer_nombre', models.CharField(db_column='primer_nombre', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, db_column='segundo_nombre', max_length=100, null=True)),
                ('primer_apellido', models.CharField(db_column='primer_apellido', max_length=100)),
                ('segundo_apellido', models.CharField(db_column='segundo_apellido', max_length=100)),
                ('cedula', models.CharField(db_column='cedula', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos.', regex='^\\d{10}$')])),
                ('fecha_nacimiento', models.DateField(db_column='fecha_nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='sexo', max_length=1)),
                ('tipo_sangre', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], db_column='tipo_sangre', max_length=3)),
                ('celular', models.CharField(db_column='celular', max_length=15, validators=[django.core.validators.RegexValidator(message='El celular debe tener entre 9 y 15 dígitos.', regex='^\\d{9,15}$')])),
                ('foto', models.ImageField(blank=True, db_column='foto', null=True, upload_to='usuarios/fotos/')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['id_usuario'],
            },
        ),
    ]
