# Generated by Django 5.2.5 on 2025-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.TextField(blank=True, db_column='foto', help_text='URL encriptada de la foto del usuario', null=True),
        ),
    ]
